# Generated by Django 3.1.5 on 2021-02-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210129_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
